### ISSUE TITLE
Any plans to update to julia 1.1?

### ISSUE THREAD

**Issue by montyvesselinov** [ExpandingMan/TimeSeriesSegmentation#1]

**Comment by ExpandingMan** [comment]
I haven't used this in quite a while and have no plans to work on it.

It's likely that had I done this more recently I would have done a number of things quite differently.

Of course, feel free to use whatever you want from this however you want in another package if you find any of it useful.

**Comment by montyvesselinov** [comment]
will try to use some of it; i may do PR or generate a new package. Thank you very much!
